name: release

on:
  push:
    tags:
      - '*'
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: build ${{ matrix.os }} ${{ matrix.py }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        # os: ["ubuntu-latest", "macos-latest"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_BUILD: "cp312-*"
          CIBW_SKIP: "*-win32 *-manylinux_i686 pp*"
          CIBW_ARCHS: native
          CIBW_BEFORE_ALL_LINUX: yum install -y openssl-devel
          CIBW_BEFORE_ALL_MACOS: brew install openssl
          CIBW_ENVIRONMENT: LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib" CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

      - name: create sdist
        run: |
          pip install build
          python -m build --sdist

      - uses: actions/upload-artifact@v4
        # only do this once
        if: matrix.os == 'ubuntu-latest'
        with:
          name: sdist
          path: "dist/*.tar.gz"

      - name: test
        run: |
          pip install dist/*.whl pytest
          pytest

  upload:
    needs: [build]
    environment: release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    - name: Copy artifacts to dist/ folder
      run: |
        mkdir -p dist/
        mv *.tar.gz dist/
        mv *.whl dist/

    - uses: pypa/gh-action-pypi-publish@v1
